import TreeD from '../../../image/Rounded rectangle.png'
import NbuBlood from '../../../image/Nbublood.png'
import NbuFor from '../../../image/Nbufor2023.png'


const mockDataActivity = [
  {
    id: 1,
    image: TreeD,
    title: "โครงการต้นไม้ล้านต้น ล้านความดี",
    location: "ศูนย์เพาะชำกล้าไม้หรือสถานีเพาะชำกล้าไม้ ในสังกัดกรมป่าไม้",
    date: "1 ธันวาคม 2565",
    hr: "2",
  },
  {
    id: 2,
    image: NbuBlood,
    title: "โครงการจิตอาสาทำความสะอาดวัดอมราวราราม",
    location: "วัดอมราวราราม",
    date: "1 ธันวาคม 2565",
    hr: "8",
  },
  {
    id: 3,
    image: NbuFor,
    title: "โครงการจิตอาสาทำความสะอาดวัดอมราวราราม",
    location: "วัดอมราวราราม",
    date: "1 ธันวาคม 2565",
    hr: "8",
  },
  {
    id: 4,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "โครงการจิตอาสาทำความสะอาดวัดอมราวราราม",
    location: "วัดอมราวราราม",
    date: "1 ธันวาคม 2565",
    hr: "8",
  },
  {
    id: 5,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "โครงการจิตอาสาทำความสะอาดวัดอมราวราราม",
    location: "วัดอมราวราราม",
    date: "1 ธันวาคม 2565",
    hr: "8",
  },
  {
    id: 6,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "โครงการจิตอาสาทำความสะอาดวัดอมราวราราม",
    location: "วัดอมราวราราม",
    date: "1 ธันวาคม 2565",
    hr: "8",
  },
  {
    id: 7,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "โครงการจิตอาสาทำความสะอาดวัดอมราวราราม",
    location: "วัดอมราวราราม",
    date: "1 ธันวาคม 2565",
    hr: "8",
  },
  {
    id: 8,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "โครงการจิตอาสาทำความสะอาดวัดอมราวราราม",
    location: "วัดอมราวราราม",
    date: "1 ธันวาคม 2565",
    hr: "8",
  },
  {
    id: 9,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "โครงการจิตอาสาทำความสะอาดวัดอมราวราราม",
    location: "วัดอมราวราราม",
    date: "1 ธันวาคม 2565",
    hr: "8",
  },
  {
    id: 10,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "โครงการจิตอาสาทำความสะอาดวัดอมราวราราม",
    location: "วัดอมราวราราม",
    date: "1 ธันวาคม 2565",
    hr: "8",
  },
  {
    id: 11,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "โครงการจิตอาสาทำความสะอาดวัดอมราวราราม",
    location: "วัดอมราวราราม",
    date: "1 ธันวาคม 2565",
    hr: "8",
  },
  {
    id: 12,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "โครงการจิตอาสาทำความสะอาดวัดอมราวราราม",
    location: "วัดอมราวราราม",
    date: "1 ธันวาคม 2565",
    hr: "8",
  },
  {
    id: 13,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 14,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 15,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 16,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 17,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 18,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 19,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 20,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 21,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 22,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 23,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 24,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 25,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 26,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 27,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 28,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 29,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 30,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
];

export default mockDataActivity;
