import TreeD from '../../../image/Rounded rectangle.png'
import NbuBlood from '../../../image/Nbublood.png'
import NbuFor from '../../../image/Nbufor2023.png'
import Detailtree from '../../../image/DetailTree.png'
import Detailtample from '../../../image/DetailTample.png'
import Image4 from '../../../image/Image4.png'
import Image5 from '../../../image/Image5.png'
import Image6 from '../../../image/Image6.png'
import Image7 from '../../../image/Image7.png'
import Image8 from '../../../image/Image8.png'
import Image9 from '../../../image/Image9.png'
import Image10 from '../../../image/Image10.png'
import Image11 from '../../../image/Image11.png'
import Image12 from '../../../image/image12.png'


const mockDataActivity = [
  {
    id: 1,
    image: TreeD,
    title: Detailtree,
    // location: "ศูนย์เพาะชำกล้าไม้หรือสถานีเพาะชำกล้าไม้ ในสังกัดกรมป่าไม้",
    // date: "1 ธันวาคม 2565",
    // hr: "2",
  },
  {
    id: 2,
    image: NbuBlood,
    title: Detailtample,
    // location: "วัดอมราวราราม",
    // date: "1 ธันวาคม 2565",
    // hr: "8",
  },
  {
    id: 3,
    image: NbuFor,
    title: Detailtample,
    // location: "วัดอมราวราราม",
    // date: "1 ธันวาคม 2565",
    // hr: "8",
  },
  {
    id: 4,
    image: Image4,
    title: Detailtample,
    // location: "วัดอมราวราราม",
    // date: "1 ธันวาคม 2565",
    // hr: "8",
  },
  {
    id: 5,
    image: Image5,
    title: Detailtample,
    // location: "วัดอมราวราราม",
    // date: "1 ธันวาคม 2565",
    // hr: "8",
  },
  {
    id: 6,
    image: Image6,
    title: Detailtample,
    // location: "วัดอมราวราราม",
    // date: "1 ธันวาคม 2565",
    // hr: "8",
  },
  {
    id: 7,
    image: Image7,
    title: Detailtample,
    // location: "วัดอมราวราราม",
    // date: "1 ธันวาคม 2565",
    // hr: "8",
  },
  {
    id: 8,
    image: Image8,
    title: Detailtample,
    // location: "วัดอมราวราราม",
    // date: "1 ธันวาคม 2565",
    // hr: "8",
  },
  {
    id: 9,
    image: Image9,
    title: Detailtample,
    // location: "วัดอมราวราราม",
    // date: "1 ธันวาคม 2565",
    // hr: "8",
  },
  {
    id: 10,
    image: Image12,
    title: Detailtample,
    // location: "วัดอมราวราราม",
    // date: "1 ธันวาคม 2565",
    // hr: "8",
  },
  {
    id: 11,
    image: Image10,
    title: Detailtample,
    // location: "วัดอมราวราราม",
    // date: "1 ธันวาคม 2565",
    // hr: "8",
  },
  {
    id: 12,
    image: Image11,
    title: Detailtample,
    // location: "วัดอมราวราราม",
    // date: "1 ธันวาคม 2565",
    // hr: "8",
  },
  {
    id: 13,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 14,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 15,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 16,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 17,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 18,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 19,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 20,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 21,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 22,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 23,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 24,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 25,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 26,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 27,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 28,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 29,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
  {
    id: 30,
    image: "https://inwfile.com/s-dl/lp4mgx.jpg",
    title: "วันนี้เราจะไปดูคลองดำน้ำตกปะการัง",
    location: "คลอง",
    date: "14 พฤศจิกายน 2565",
    hr: "8",
  },
];

export default mockDataActivity;
