export const mockGrade = [
  {
    id: 1,
    term: "1/2564",
    code_subject: "SWE232",
    student_id: "621102685",
    student_fullname: "เจษฎา ซื้อสวัสดิ์",
    name_subject: "Database System Design",
    subject_unit: "3",
    grade_gpx: "A",
  },
  {
    id: 2,
    term: "1/2564",
    code_subject: "SWE232",
    student_id: "621109360",
    student_fullname: "เอกพล โตเจริญ",
    name_subject: "Database System Design",
    subject_unit: "3",
    grade_gpx: "A",
  },
  {
    id: 3,
    term: "1/2564",
    code_subject: "SWE232",
    student_id: "621111391",
    student_fullname: "ระพีพัฒน์ สุวรรณทอง",
    name_subject: "Database System Design",
    subject_unit: "3",
    grade_gpx: "A",
  },
  {
    id: 4,
    term: "1/2564",
    code_subject: "SWE232",
    student_id: "621112703",
    student_fullname: "พัชช์ฐณณท์ เจริญเปี่ยม",
    name_subject: "Database System Design",
    subject_unit: "3",
    grade_gpx: "A",
  },
  {
    id: 5,
    term: "1/2564",
    code_subject: "SWE232",
    student_id: "621113759",
    student_fullname: "ศุภกร กลีบพุฒ",
    name_subject: "Database System Design",
    subject_unit: "3",
    grade_gpx: "A",
  },
];
