export const mockDataTimeTable = [
  {
    term: "2/2565",
    code_subject: "SWE232",
    name_subject: "Database System Design I",
    group: "1",
    wkday: "MON",
    distance: "09:00-12:00",
    teacher_on_subject: "ผศ.เจษฎา ซื้อสวัสดิ์",
  },
  {
    term: "2/2565",
    code_subject: "SWE233",
    name_subject: "Database System Design II",
    group: "1",
    wkday: "TUE",
    distance: "09:00-12:00",
    teacher_on_subject: "ผศ.เอกพล โตเจริญ",
  },
  {
    term: "2/2565",
    code_subject: "SWE332",
    name_subject: "Database System Design III",
    group: "1",
    wkday: "WED",
    distance: "09:00-12:00",
    teacher_on_subject: "ผศ.ระพีพัฒน์ สุวรรณทอง",
  },
  {
    term: "2/2565",
    code_subject: "SWE331",
    name_subject: "Database System Design IV",
    group: "1",
    wkday: "THU",
    distance: "09:00-12:00",
    teacher_on_subject: "ผศ.พัชช์ฐณนท์ เจริญเปี่ยม",
  },
  {
    term: "2/2565",
    code_subject: "SWE432",
    name_subject: "Database System Design V",
    group: "1",
    wkday: "FRi",
    distance: "09:00-12:00",
    teacher_on_subject: "ผศ.ศุภกร กลีบพุฒ",
  },
];
