export const activityHoursListDataMock = [
  {
    id: 1,
    term: "2/2565",
    name_activity: "Big Cleaning Day 2022",
    student_id: "621102685",
    student_fullname: "เจษฎา ซื้อสวัสดิ์",
    activity_hours: "6",
    position: "ผู้เข้าร่วม",
  },
  {
    id: 2,
    term: "2/2565",
    name_activity: "Big Cleaning Day 2022",
    student_id: "621109360",
    student_fullname: "เอกพล โตเจริญ",
    activity_hours: "6",
    position: "ผู้เข้าร่วม",
  },
  {
    id: 3,
    term: "2/2565",
    name_activity: "Big Cleaning Day 2022",
    student_id: "621111391",
    student_fullname: "ระพีพัฒน์ สุวรรณทอง",
    activity_hours: "6",
    position: "ผู้เข้าร่วม",
  },
  {
    id: 4,
    term: "2/2565",
    name_activity: "Big Cleaning Day 2022",
    student_id: "621112703",
    student_fullname: "พัชช์ฐณณท์ เจริญเปี่ยม",
    activity_hours: "6",
    position: "ผู้เข้าร่วม",
  },
  {
    id: 5,
    term: "2/2565",
    name_activity: "Big Cleaning Day 2022",
    student_id: "621113759",
    student_fullname: "ศุภกร กลีบพุฒ",
    activity_hours: "6",
    position: "ผู้เข้าร่วม",
  },
];
