const default_user = {
  username: "",
  password: "",
  student_id: "",
  user_image: "",
  id_number: "",
  prefix_name: "",
  user_first_name_th: "",
  user_last_name_th: "",
  user_first_name_eng: "",
  user_last_name_eng: "",
  faculty: "",
  major: "",
  year: "",
  model_name: "",
  class_year_student: "",
  student_email_education: "",
  student_status: "",
  phone_number_home: "",
  phone_number: "",
  last_address: "",
  last_level_student: "",
  old_school: "",
  last_major: "",
  year_end_old_school: "",
  gpx_hight_school: "",
  user_status: false,
};
