export const mockPerformance = [
  {
    term: "2/2565",
    date_on_submit: "12/12/2565",
    user_fullname: "เจษฎา ซื้อสวัสดิ์",
    name_of_performance: "การแข่งขันตอบคำถามวิชาการ ประจำปี 2565",
    name_of_reward: "รางวัลชนะเลิศการแข่งขันตอบคำถาม ประจำปี 2565",
    type_of_performance: "ผลงานภายใน",
  },
  {
    term: "2/2565",
    date_on_submit: "07/12/2565",
    user_fullname: "เอกพล โตเจริญ",
    name_of_performance: "การแข่งขันตอบคำถามวิชาการ ประจำปี 2565",
    name_of_reward: "รางวัลชนะเลิศการแข่งขันตอบคำถาม ประจำปี 2565",
    type_of_performance: "ผลงานภายใน",
  },
  {
    term: "2/2565",
    date_on_submit: "27/11/2565",
    user_fullname: "ระพีพัฒน์ สุวรรณทอง",
    name_of_performance: "การแข่งขันตอบคำถามวิชาการ ประจำปี 2565",
    name_of_reward: "รางวัลชนะเลิศการแข่งขันตอบคำถาม ประจำปี 2565",
    type_of_performance: "ผลงานภายใน",
  },
  {
    term: "2/2565",
    date_on_submit: "26/11/2565",
    user_fullname: "พัชช์ฐณณท์ เจริญเปี่ยม",
    name_of_performance: "การแข่งขันตอบคำถามวิชาการ ประจำปี 2565",
    name_of_reward: "รางวัลชนะเลิศการแข่งขันตอบคำถาม ประจำปี 2565",
    type_of_performance: "ผลงานภายใน",
  },
  {
    term: "2/2565",
    date_on_submit: "23/11/2565",
    user_fullname: "ศุภกร กลีบพุฒ",
    name_of_performance: "การแข่งขันตอบคำถามวิชาการ ประจำปี 2565",
    name_of_reward: "รางวัลชนะเลิศการแข่งขันตอบคำถาม ประจำปี 2565",
    type_of_performance: "ผลงานภายใน",
  },
];
