export const mockDataCapitalBurden = [
  {
    id: 8,
    name: "พัชช์ฐณณท์ เจริญเปี่ยม",
    term: "1/2565",
    type_capital: "E50",
    capital: "ทุนเรียนดี 50%",
    money: "12,180",
  },
  {
    id: 7,
    name: "ศุภกร กรีบพุฒ",
    term: "1/2565",
    type_capital: "E30",
    capital: "ทุนเรียนดี 30%",
    money: "12,180",
  },
  {
    id: 6,
    name: "พัชช์ฐณณท์ เจริญเปี่ยม",
    term: "2/2565",
    type_capital: "E50",
    capital: "ทุนเรียนดี 50%",
    money: "14,880",
  },
  {
    id: 5,
    name: "ศุภกร กรีบพุฒ",
    term: "2/2565",
    type_capital: "E30",
    capital: "ทุนเรียนดี 30%",
    money: "14,880",
  },
  {
    id: 4,
    name: "พัชช์ฐณณท์ เจริญเปี่ยม",
    term: "1/2565",
    type_capital: "E50",
    capital: "ทุนเรียนดี 50%",
    money: "12,190",
  },
  {
    id: 3,
    name: "ศุภกร กรีบพุฒ",
    term: "1/2565",
    type_capital: "E30",
    capital: "ทุนเรียนดี 30%",
    money: "12,190",
  },
  {
    id: 2,
    name: "พัชช์ฐณณท์ เจริญเปี่ยม",
    term: "2/2565",
    type_capital: "E50",
    capital: "ทุนเรียนดี 50%",
    money: "14,180",
  },
  {
    id: 1,
    name: "ศุภกร กรีบพุฒ",
    term: "2/2565",
    type_capital: "E30",
    capital: "ทุนเรียนดี 30%",
    money: "14,180",
  },
];
