export const mockDataParacapital = [
  {
    term: "1/2562",
    capital: "ทุน เรียนดี 30%",
    money: "32,020",
    remaining: "26,020",
    type: "E30",
    funder: " มหาวิทยาลัยนอร์ทกรุงเทพ ",
    capitalDiscount: "0",
  },
  {
    term: "1/2562",
    capital: "ทุน เรียนดี 30%",
    money: " - ",
    remaining: "-",
    type: "E30",
    funder: " มหาวิทยาลัยนอร์ทกรุงเทพ",
    capitalDiscount: "9,000",
  },
  {
    term: "2/2562",
    capital: "ทุน เรียนดี 30%",
    money: " - ",
    remaining: "-",
    type: "E30",
    funder: " มหาวิทยาลัยนอร์ทกรุงเทพ ",
    capitalDiscount: "9,000",
  },
  {
    term: "2/2562",
    capital: "ทุน เรียนดี 30%",
    money: "26,020",
    remaining: "-",
    type: "E30",
    funder: " มหาวิทยาลัยนอร์ทกรุงเทพ ",
    capitalDiscount: "0",
  },
  {
    term: "3/2562",
    capital: "ทุน เรียนดี 30%",
    money: " - ",
    remaining: "-",
    type: "E30",
    funder: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    capitalDiscount: "9,000",
  },
  {
    term: "1/2563",
    capital: "ทุน เรียนดี 30%",
    money: " - ",
    remaining: "-",
    type: "E30",
    funder: " มหาวิทยาลัยนอร์ทกรุงเทพ ",
    capitalDiscount: "9,000",
  },
  {
    term: "1/2563",
    capital: "ทุน เรียนดี 30%",
    money: "26,020",
    remaining: "-",
    type: "E30",
    funder: " มหาวิทยาลัยนอร์ทกรุงเทพ ",
    capitalDiscount: "0",
  },
  // {
  //   term: "2/2563",
  //   capital: "ทุน เรียนดี 30%",
  //   money: " - ",
  //   get: " - ",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "9,000",
  // },
  // {
  //   term: "2/2563",
  //   capital: "190299 : ทุนกู้ยืมลักษณะที่ 2(กรอ.)",
  //   money: "26,020",
  //   get: "26,020",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "0",
  // },
  // {
  //   term: "1/2564",
  //   capital: "ทุน เรียนดี 30%",
  //   money: " - ",
  //   get: " - ",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "9,000",
  // },
  // {
  //   term: "1/2564",
  //   capital: "190299 : ส่วนลดค่าบำรุงการศึกษา",
  //   money: " - ",
  //   get: " - ",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "9,000",
  // },
  // {
  //   term: "1/2564",
  //   capital: "190299 : ทุนกู้ยืมลักษณะที่ 2(กรอ.)",
  //   money: "26,020",
  //   get: "26,020",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "0",
  // },
  // {
  //   term: "1/2564",
  //   capital: "190299 : ทุนกู้ยืมลักษณะที่ 2(กรอ.)",
  //   money: "26,020",
  //   get: "26,020",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "0",
  // },
  // {
  //   term: "2/2564",
  //   capital: "1110113 : ทุน IT เรียนดี 30%",
  //   money: " - ",
  //   get: " - ",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "9,000",
  // },
  // {
  //   term: "2/2564",
  //   capital: "190299 : ทุนกู้ยืมลักษณะที่ 2(กรอ.)",
  //   money: "26,020",
  //   get: "26,020",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "0",
  // },
  // {
  //   term: "3/2564",
  //   capital: "1110113 : ทุน IT เรียนดี 30%",
  //   money: " - ",
  //   get: " - ",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "9,000",
  // },
  // {
  //   term: "1/2565",
  //   capital: "1110113 : ทุน IT เรียนดี 30%",
  //   money: " - ",
  //   get: " - ",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "9,000",
  // },
  // {
  //   term: "1/2565",
  //   capital: "190299 : ทุนกู้ยืมลักษณะที่ 2(กรอ.)",
  //   money: "26,020",
  //   get: "26,020",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "0",
  // },
  // {
  //   term: "2/2565",
  //   capital: "1110113 : ทุน IT เรียนดี 30%",
  //   money: " - ",
  //   get: " - ",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "9,000",
  // },
  // {
  //   term: "2/2565",
  //   capital: "190299 : ทุนกู้ยืมลักษณะที่ 2(กรอ.)",
  //   money: "-",
  //   get: "-",
  //   remaining: "-",
  //   type: "E30",
  //   funder: " - ",
  //   capitalDiscount: "0",
  // },
];
