import image from "../../../image/Image.png"
import Thebest from "../../../image/Thebest.png"
import SBAC from "../../../image/SBACRUN.png"
import Quiz from "../../../image/Quiz.png"
import QuizOut from "../../../image/QuizOut.png"
import Noimg from "../../../image/Defaultnbu.png"
import DetailThebest from "../../../image/DetailThebest.png"
import DetailSBAC from "../../../image/DetailSBACl.png"
import DetailQuiz from "../../../image/DetailQuiz.png"
const mockDataActivity = [
  {
    id: 1,
    image: Thebest,
    title: DetailThebest,
    // location: "พิพิธภัณฑ์วิทยาศาสตร์แห่งชาติ คลองห้า",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายนอก",
  },
  {
    id: 2,
    image: SBAC,
    title: DetailSBAC,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 3,
    image: Quiz,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 4,
    image: QuizOut,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 5,
    image: SBAC,
    title: DetailSBAC,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายนอก",
  },
  {
    id: 6,
    image: Quiz,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายนอก",
  },
  {
    id: 7,
    image: Noimg,
    title:DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 8,
    image: SBAC,
    title: DetailSBAC,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 9,
    image: Quiz,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายนอก",
  },
  {
    id: 10,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 11,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 12,
    image: QuizOut,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 13,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายนอก",
  },
  {
    id: 14,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 15,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายนอก",
  },
  {
    id: 16,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 17,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 18,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 19,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายนอก",
  },
  {
    id: 20,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
  {
    id: 21,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายนอก",
  },
  {
    id: 22,
    image: Noimg,
    title: DetailQuiz,
    // location: "มหาวิทยาลัยนอร์ทกรุงเทพ",
    // date: "1 ธันวาคม 2565",
    // hr: "รางวัลภายใน",
  },
];

export default mockDataActivity;
